### PR TITLE
Fixed foot drive issues, updated baud rate to new standard, clarified variable names, updated dome code to new version of Android

### PR DESCRIPTION
**Pull request by rcorvus**
Fixed foot drive issues, updated baud rate to new standard, clarified variable names, updated dome code to new version of Android

### CODE REVIEW

**Comment by rcorvus** [comment]
I hope this helps, thanks again for converting the Padawan to the Xbox360 controller!!!

**Comment by dankraus** [comment]
@rcorvus  - Not sure if it was an accident but you closed this. I'm reopening.

**Comment by rcorvus** [comment]
Ok thanks

**Comment by dankraus** [comment]
@rcorvus - I finally had a chance to look over your changes against what I have running.

Can you explain the issues you had with the `turnthrottle` stuff. I'm not seeing any issues with turning near as I can tell.  As to why I had it the way I did, I couldn't telly out. It's been a long time! I'm not having that speed issue you mentioned...

Did change eliminate the need for doing negative turn throttle in? `ST.turn(-turnThrottle)`; 

I'm at a con right now with my droid and don't have a USB cable on my to try it out.

Thanks for clearing up the variable names.

**Comment by dankraus** [comment]
Hey @rcorvus , I incorporated a bunch of your fixes. I had made some variable name tweaks along the way so there a whole bunch of merge conflicts. Incorporated some controller shutoff button combo someone had shown in the thread on Astromech. If this was a project at work, I'd take the time to do this right but....

Most notably, I took your Dome changes and dropped them right in. Your revised credit still remains in there of course. I'm going to leave the baud rates in there as is. I have the baud rate options in the docs and in the code as options.

Thanks for your contributions and sorry I'm only now formally closing this. I had cracked it open a few times over the last few months.

**Comment by rcorvus** [comment]
Ok cool, thanks for letting me know!

**Pull request closed without merging**
